-- Add more job listings including the LinkedIn Onsite Supervisor position
-- Run this in Supabase SQL Editor

-- First, check if jobs table exists and clear any existing sample data if needed
-- DELETE FROM public.jobs WHERE title IN ('Warehouse Associate', 'Office Administrator', 'Retail Sales Associate', 'Call Center Representative', 'Janitorial Technician');

-- Insert the LinkedIn job posting and additional jobs
INSERT INTO public.jobs (
    title, 
    description, 
    requirements, 
    location_city, 
    location_state, 
    location_zip, 
    job_type, 
    category, 
    salary_min, 
    salary_max, 
    salary_type, 
    is_active, 
    featured
)
VALUES
    -- LinkedIn Onsite Supervisor position
    (
        'Onsite Supervisor',
        'The Onsite Supervisor will oversee the day-to-day operations of staffing and workforce management at client locations. Responsibilities include managing employee schedules, addressing staffing needs, resolving conflicts or issues, ensuring compliance with company policies and procedures, and fostering a collaborative work environment. The Supervisor will serve as a key liaison between the on-site team and management, ensuring smooth communication and efficient operations.',
        'Leadership and team management skills; Strong problem-solving and decision-making abilities; Excellent organizational and time-management skills; Proficient communication and interpersonal skills; Experience in staffing, workforce management, or related field (preferred); Familiarity with workplace compliance standards; High school diploma or GED required; Bilingual (English-Spanish) preferred',
        'Piscataway',
        'NJ',
        '08854',
        'full-time',
        'Management',
        59306,
        76702,
        'annual',
        true,
        true
    ),
    -- Additional diverse job listings
    (
        'Administrative Assistant',
        'Support office operations with administrative tasks including scheduling, data entry, and customer communication. Perfect for detail-oriented individuals.',
        'High school diploma; Proficiency in MS Office; Strong communication skills; 1+ years office experience preferred',
        'Laurel',
        'MD',
        '20707',
        'full-time',
        'Administrative & Clerical',
        32000,
        38000,
        'annual',
        true,
        false
    ),
    (
        'Forklift Operator',
        'Operate forklift equipment to move materials in warehouse environment. Day and night shifts available.',
        'Valid forklift certification; 1 year experience; Ability to work in fast-paced environment; Pass drug screening',
        'Jessup',
        'MD',
        '20794',
        'full-time',
        'Industrial & Manufacturing',
        18,
        22,
        'hourly',
        true,
        true
    ),
    (
        'Customer Service Representative',
        'Provide excellent customer service via phone and email. Remote position available.',
        'High school diploma; Excellent verbal and written communication; Computer proficiency; Previous customer service experience',
        'Greenbelt',
        'MD',
        '20770',
        'full-time',
        'Call Center & Customer Service',
        33000,
        40000,
        'annual',
        true,
        false
    ),
    (
        'Production Worker',
        'Join our production team in a clean, climate-controlled facility. No experience necessary - we train!',
        'Ability to stand for extended periods; Attention to detail; Reliable transportation; Pass background check',
        'Beltsville',
        'MD',
        '20705',
        'full-time',
        'Industrial & Manufacturing',
        16,
        19,
        'hourly',
        true,
        false
    ),
    (
        'Medical Receptionist',
        'Front desk position in busy medical office. Handle patient scheduling and insurance verification.',
        'Medical terminology knowledge; Experience with EMR systems; Professional demeanor; Bilingual Spanish preferred',
        'Silver Spring',
        'MD',
        '20910',
        'full-time',
        'Healthcare',
        36000,
        42000,
        'annual',
        true,
        false
    ),
    (
        'Delivery Driver',
        'Local delivery routes with company vehicle provided. Home daily.',
        'Valid driver license with clean record; DOT physical required; GPS navigation skills; Customer service oriented',
        'Capitol Heights',
        'MD',
        '20743',
        'full-time',
        'Transportation',
        17,
        21,
        'hourly',
        true,
        true
    ),
    (
        'IT Support Technician',
        'Provide technical support for hardware and software issues. Great opportunity for entry-level IT professionals.',
        'CompTIA A+ preferred; Windows/Mac OS knowledge; Problem-solving skills; Customer service experience',
        'Rockville',
        'MD',
        '20850',
        'contract',
        'Technology',
        45000,
        55000,
        'annual',
        true,
        false
    ),
    (
        'Retail Manager',
        'Lead retail team in busy store environment. Responsible for sales, inventory, and staff management.',
        '2+ years retail management; Strong leadership skills; POS system experience; Flexible schedule required',
        'Waldorf',
        'MD',
        '20602',
        'full-time',
        'Retail & Sales',
        42000,
        52000,
        'annual',
        true,
        false
    ),
    (
        'Accounting Clerk',
        'Process invoices, maintain records, and assist with month-end closing.',
        'Associates degree in accounting preferred; QuickBooks experience; Detail-oriented; Excel proficiency',
        'Bethesda',
        'MD',
        '20814',
        'full-time',
        'Finance',
        38000,
        45000,
        'annual',
        true,
        false
    ),
    (
        'Security Officer',
        'Protect property and ensure safety at commercial locations. Various shifts available.',
        'Security license required; Clean criminal background; Professional appearance; Communication skills',
        'Alexandria',
        'VA',
        '22314',
        'full-time',
        'Security',
        16,
        20,
        'hourly',
        true,
        false
    ),
    (
        'Food Service Worker',
        'Join our cafeteria team preparing and serving meals. Morning shift.',
        'Food handling certificate; Team player; Stand for extended periods; Weekend availability',
        'Gaithersburg',
        'MD',
        '20877',
        'part-time',
        'Food Service',
        14,
        17,
        'hourly',
        true,
        false
    ),
    (
        'HR Assistant',
        'Support HR department with recruiting, onboarding, and employee relations.',
        'Bachelor degree preferred; HRIS experience; Confidentiality; Strong organizational skills',
        'Tysons',
        'VA',
        '22102',
        'full-time',
        'Human Resources',
        40000,
        48000,
        'annual',
        true,
        true
    ),
    (
        'Maintenance Technician',
        'Perform preventive maintenance and repairs on facility equipment.',
        'Trade school or equivalent experience; Basic electrical/plumbing knowledge; Own tools; On-call availability',
        'Landover',
        'MD',
        '20785',
        'full-time',
        'Maintenance',
        20,
        26,
        'hourly',
        true,
        false
    ),
    (
        'Data Entry Specialist',
        'Remote position entering data with accuracy and speed. Flexible hours available.',
        'Typing speed 50+ WPM; Attention to detail; Computer proficiency; Work from home setup',
        'Remote',
        'MD',
        '20001',
        'contract',
        'Administrative & Clerical',
        15,
        18,
        'hourly',
        true,
        false
    ),
    (
        'Sales Representative',
        'B2B sales position with base plus commission. Excellent earning potential.',
        'Proven sales track record; Self-motivated; Valid driver license; Professional presentation',
        'Columbia',
        'MD',
        '21044',
        'full-time',
        'Sales',
        45000,
        75000,
        'annual',
        true,
        true
    ),
    (
        'Assembly Technician',
        'Assemble electronic components following blueprints and specifications.',
        'Manual dexterity; Read blueprints; Quality focus; Stand/sit for long periods',
        'Germantown',
        'MD',
        '20874',
        'full-time',
        'Industrial & Manufacturing',
        17,
        21,
        'hourly',
        true,
        false
    ),
    (
        'Bookkeeper',
        'Maintain financial records for multiple clients. Part-time with potential for full-time.',
        'Bookkeeping certification; QuickBooks proficiency; 3+ years experience; Detail-oriented',
        'Annapolis',
        'MD',
        '21401',
        'part-time',
        'Finance',
        22,
        28,
        'hourly',
        true,
        false
    ),
    (
        'Receptionist',
        'First point of contact for professional services firm. Greet visitors and manage phones.',
        'Professional appearance; Multi-line phone experience; Computer skills; Positive attitude',
        'Arlington',
        'VA',
        '22201',
        'full-time',
        'Administrative & Clerical',
        32000,
        38000,
        'annual',
        true,
        false
    ),
    (
        'Machine Operator',
        'Operate production machinery in manufacturing facility. Training provided.',
        'Mechanical aptitude; Follow safety procedures; High school diploma; Drug-free workplace',
        'Baltimore',
        'MD',
        '21230',
        'full-time',
        'Industrial & Manufacturing',
        18,
        23,
        'hourly',
        true,
        true
    );

-- Update the featured status for some jobs to ensure variety
UPDATE public.jobs 
SET featured = true 
WHERE title IN ('Forklift Operator', 'Delivery Driver', 'HR Assistant', 'Sales Representative', 'Machine Operator')
AND featured = false;
